#!/bin/sh

JSON_STRING='
window.configs = { 
  "VUE_APP_EMPRESAS_API":"'"${VUE_APP_EMPRESAS_API}"'", 
  "VUE_APP_KEYCLOAK_AUTH_URL":"'"${VUE_APP_KEYCLOAK_AUTH_URL}"'",
  "VUE_APP_KEYCLOAK_REALM":"'"${VUE_APP_KEYCLOAK_REALM}"'",
  "VUE_APP_KEYCLOAK_CLIENT_ID":"'"${VUE_APP_KEYCLOAK_CLIENT_ID}"'",
  "VUE_APP_KEYCLOAK_MINVALIDITY":"'"${VUE_APP_KEYCLOAK_MINVALIDITY}"'"
}'

sed -i "s@// CONFIGURATIONS_PLACEHOLDER@${JSON_STRING}@" /app/index.html

exec "$@"
