kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.Values.app.name}}
data:
  VUE_APP_KEYCLOAK_CLIENT_ID: "deltacare"
  VUE_APP_KEYCLOAK_MINVALIDITY: "70"
  VUE_APP_KEYCLOAK_AUTH_URL: "https://sso.deltacare.xyz/auth"
  VUE_APP_EMPRESAS_API_DEV: "https://dev.deltacare.xyz/api/v1/empresas"
  VUE_APP_PRODUTOS_API_DEV: "https://dev.deltacare.xyz/api/v1/produtos"
  VUE_APP_FATURAS_API_DEV: "https://dev.deltacare.xyz/api/v1/faturas"
  VUE_APP_PAINEL_API_DEV: "https://dev.deltacare.xyz/api/v1/painel"
  VUE_APP_KEYCLOAK_REALM_DEV: "Deltacare-DEV"
  VUE_APP_EMPRESAS_API_PRD: "https://app.deltacare.xyz/api/v1/empresas"
  VUE_APP_PRODUTOS_API_PRD: "https://app.deltacare.xyz/api/v1/produtos"
  VUE_APP_FATURAS_API_PRD: "https://app.deltacare.xyz/api/v1/faturas"
  VUE_APP_PAINEL_API_PRD: "https://app.deltacare.xyz/api/v1/painel"
  VUE_APP_KEYCLOAK_REALM_PRD: "Deltacare-PRD"
