apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.app.name}}
spec:
  hosts:
    - dev.deltacare.xyz
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /
      name: {{.Values.app.name}}
      route:
        - destination:
            host: {{.Values.app.name}}
            port:
              number: {{.Values.service.port}}