apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-src.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "web-src.selectorLabels" . | nindent 4 }}
