apiVersion: v2
name: web-src
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# O valor desse parâmetro é sobrescrito pelo valor do parâmetro image.tag passado quando jenkins 
# executa o comando helm upgrade. Para isso, /templates/_helpers.tpl foi alterado. Dessa forma, 
# o valor desse parâmetro é definido no pipeline para garantir a coesão com a versão definida 
# no código do app (package.json, pom.xml etc). Por: David Carvalho.
appVersion: 0.1.0
